/*
 * This source file was generated by the Gradle 'init' task
 */
package tubes;

import tubes.views.rendering;

public class App {

    public static void main(String[] args) {
        rendering app = new rendering();
        app.start();
    }
}